# Generated by Django 4.0.1 on 2022-01-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upload',
            field=models.ImageField(default='  ', upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
