# Generated by Django 4.0.1 on 2022-01-21 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articl', '0002_post_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upload',
            new_name='cover',
        ),
    ]
