# Generated by Django 4.0.1 on 2022-01-21 16:35

import articl.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articl', '0003_rename_upload_post_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='book',
            field=models.FileField(default='  ', upload_to='books/%Y-%m-%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='cover',
            field=models.ImageField(upload_to=articl.models.user_directory_path),
        ),
    ]
